version: '3.1'

services:
  ubuntu:
    build: ./ubuntu
    stdin_open: true
    image: mamasad/sabratdocejzam-ubuntu:latest
  
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    image: mamasad/sabratdocejzam-nginx:latest 